sot_controller:
  mobile_base_controller: /mobile_base_controller
  map_rc_to_sot_device: {
    motor-angles: motor-angles,
    joint-angles: joint-angles,
    velocities: velocities,
    torques: torques,
    cmd-joints: control,
    cmd-effort: control,
    cmd-base-vel: base-vel,
    odometry: odometry
  }
  control_mode: POSITION
